---
title: "Lab3"
author: "Blanco Romain, Carlin Cyril, Dong Stéphane"
date: "02/26/2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}
NAm2 <- read.table ("NAm2.txt", header = T)
cont<-function(x)
  {
    if (x %in% c("Canada"))
      cont<-"NorthAmerica"
    else if (x %in% c("Guatemala","Mexico","Panama","CostaRica"))
      cont<-"CentralAmerica"
    else
      cont<-"SouthAmerica"
    return (factor(cont))
  }
contID<-sapply(as.character(NAm2[,4]),FUN=cont)
```

### Question a

```{r, warning=FALSE, error=TRUE}
# Libraries needed
library("class")
library("MASS")

NAcont<-cbind(contID=contID,NAm2[,-(1:8)])
NAcont[,1]<-factor(NAcont[,1])
labels <-rep (1: 2, each=494/2); set = sample(labels, 494)
# Doesn't work because the variance-covariance matrix is not inversible
ldaModel <- lda(contID~., NAcont[1:1000,], subset=which(set==1))
```


### Question b

```{r}
# We remove markers that have a null variance
withinvar<-apply(NAcont[(set==1),-1],FUN=
                   function(x){tapply(x,NAcont[(set==1),1],FUN=var)},MARGIN=2)
bool<-as.logical(apply(withinvar,FUN=function(x){prod(x!=0)},MARGIN=2))
NAcont2<-cbind(contID=contID,(NAm2[,-(1:8)])[,bool])
NAcont2[,1]<-factor(NAcont[,1])
length(NAcont2) # 3128 remaining markers
fit <- lda(contID~., NAcont2, subset = which(set==1))
summary(fit)


```

### Question c

```{r}
# Use of model to predict test set
prediction <- predict(fit, NAcont2[which(set==2),], type=c("class"))
summary(prediction)
```

### Question d

```{r}
# Confusion matrix
confMatrix <- table(NAcont2[which(set==2),1],prediction$class)
confMatrix
# Display barplot
mycol<-c("black","grey40","lightgrey")
barplot(t(confMatrix),col=mycol)
legend("topleft",paste(1:3),col=mycol,lwd=2,cex=2)
```

### Question e

```{r}
missclass<-function(x) {
  errorMean = 0;
  for(i in 1:length(x[1,]))
    for(j in 1:length((x[,1])))
      if(i != j)
        errorMean = errorMean + x[i,j]
  errorMean = errorMean/sum(x)
  print(errorMean)
}
missclass(confMatrix)
```

### Question f

```{r,warning=FALSE}
# Operating a cross-validation with LDA method
l <- length(NAcont2$contID)
labels=rep(1:10,each=50, length.out = l)
set=sample(labels,l)
predictedID = matrix(nrow = l, ncol = 1)
for(i in 1:10) {
  fit <- lda(contID~., NAcont2, subset = which(set!=i))
  predictedID[which(set==i),1] <- (predict(fit,NAcont2[which(set==i),], type=c("class")))$class
}

# Confusion Matrix
confMatrix2 <- table(NAcont2[,1],predictedID)
confMatrix2

# Display barplot
mycol<-c("black","grey40","lightgrey")
barplot(t(confMatrix2),col=mycol)
legend("topleft",paste(1:3),col=mycol,lwd=2,cex=2)

# Rate of missclassified individuals
missclass(confMatrix2)
```